project_name: shinecosucan
env: test

instances:
  - name: vendure-db
    db_name: vendure
    username: postgres

    engine:
      type: postgres
      version: VER_17

    instance_class: BURSTABLE3
    instance_size: MICRO

    vpc: main
    security_group_name: db
    subnet_type: PUBLIC
    availability_zones:
      - eu-west-1a
      - eu-west-1b
    publicly_accessible: true
    port: 5432

    allocated_storage_gb: 20
    storage_encrypted: false

    multi_az: false
    deletion_protection: false

    backup_retention_days: 0

    parameter_group_params:
      rds.force_ssl: "0"

    password_length: 12


