project_name: shinecosucan
env: test

instances:
  - name: vendure-db
    db_name: vendure
    username: postgres
    engine_version: "17"
    instance_class: BURSTABLE3
    instance_size: MICRO
    multi_az: false
    storage_encrypted: false
    deletion_protection: false
    subnet_type: PUBLIC
    port: 5432
    vpc: main
    security_group_name: db-sg
    availability_zones:
      - eu-west-1a
      - eu-west-1b
    parameter_group:
      rds.force_ssl: "0"

#  - name: analytics-db
#    db_name: analytics
#    username: analyst
#    engine_version: "17"
#    instance_class: BURSTABLE3
#    instance_size: MICRO
#    multi_az: false
#    storage_encrypted: false
#    deletion_protection: false
#    subnet_type: PUBLIC
#    port: 5432
#    vpc: main
#    security_group_name: db-sg
#    availability_zones:
#      - eu-west-1a
#      - eu-west-1b
