project_name: shinecosucan
env: test

albs:
  - name: app-alb
    vpc: main
    availability_zones:
      - eu-west-1a
      - eu-west-1b
    domain_name: dev.yospace.ai
    subdomains:
      - name: shinecosucan-app
        port: 8002
        path: /
      - name: shinecosucan-admin
        port: 3000
        path: /health
    sg: alb-sg

  - name: admin-alb
    vpc: main
    availability_zones:
      - eu-west-1a
      - eu-west-1b
    domain_name: dev.yospace.ai
    subdomains:
      - name: shinecosucan-test
        port: 3000
        path: /health
    sg: alb-sg
