project_name: shinecosucan
env: test

albs:
  - name: main-alb
    vpc: main
    availability_zones:
      - eu-west-1a
      - eu-west-1b
    internet_facing: true
    sg: alb
    domain_name: dev.yospace.ai
    certificate:
      id: main-alb-cert
      type: create
      main_subdomain: shinecosucan-app
      alt_subdomains:
        - shinecosucan-admin
      hosted_zone_name: dev.yospace.ai
    http_redirect_to_https:
      enabled: true
      permanent: true
    default_https_action:
      type: fixed_response
      status_code: 404
      message_body: "The requested resource could not be found."
      content_type: "text/plain"
    target_groups:
      - name: frontend-tg
        port: 8002
        protocol: HTTP
        target_type: INSTANCE
        health_check:
          path: /
          healthy_http_codes: "200"
          interval_seconds: 30
          timeout_seconds: 5
          healthy_threshold: 2
          unhealthy_threshold: 2
        host_headers:
            - shinecosucan-app
        action:
          type: forward
          target_group_name_ref: frontend-tg
      - name: backend-tg
        port: 3000
        protocol: HTTP
        target_type: INSTANCE
        health_check:
          path: /health
          healthy_http_codes: "200"
        host_headers:
          - shinecosucan-admin
        action:
          type: forward
          target_group_name_ref: backend-tg
