project_name: shinecosucan
env: test

security_groups:
  - name: alb
    description: Security group for ALB
    vpc: main
    availability_zones:
      - eu-west-1a
      - eu-west-1b
    allow_all_outbound: true
    ingress:
      - port: 80
        protocol: tcp
        cidr: "0.0.0.0/0"
        description: Allow HTTP traffic
      - port: 443
        protocol: tcp
        cidr: "0.0.0.0/0"
        description: Allow HTTPS traffic

  - name: frontend

    description: Security group for frontend
    vpc: main
    availability_zones:
      - eu-west-1a
      - eu-west-1b
    allow_all_outbound: true
    ingress:
      - port: -1
        protocol: all
        source_sg: alb
        description: Allow all traffic from ALB
      - port: 22
        protocol: tcp
        cidr: "0.0.0.0/0"
        description: Allow SSH traffic

  - name: backend
    description: Security group for backend
    vpc: main
    availability_zones:
      - eu-west-1a
      - eu-west-1b
    allow_all_outbound: true
    ingress:
      - port: -1
        protocol: all
        source_sg: alb
        description: Allow all traffic from ALB
      - port: 3000
        protocol: tcp
        source_sg: frontend
        description: Allow traffic from frontend
      - port: 22
        protocol: tcp
        cidr: "0.0.0.0/0"
        description: Allow SSH

  - name: db
    description: Security group for PostgreSQL DB
    vpc: main
    availability_zones:
      - eu-west-1a
      - eu-west-1b
    allow_all_outbound: true
    ingress:
      - port: 5432
        protocol: tcp
        source_sg: backend
        description: Allow PostgreSQL traffic from backend
