env: test
project_name: shinecosucan

vpcs:
  - name: main
    cidr: "10.0.0.0/16"
    max_azs: 2
    nat_gateways: 0
    subnets:
      - name: Public
        type: PUBLIC
        cidr_mask: 24
      - name: Private
        type: PRIVATE_ISOLATED
        cidr_mask: 24

  - name: secondary
    cidr: "10.1.0.0/16"
    max_azs: 2
    subnets:
      - name: public
        type: PUBLIC
        cidr_mask: 24