project_name: shinecosucan
env: test
vpc: main

availability_zones:
  - eu-west-1a
  - eu-west-1b

instance_type: t3.small
asg_min_capacity: 1
asg_max_capacity: 4
asg_desired_capacity: 2

services:
  frontend:
    image: "577638398727.dkr.ecr.eu-west-1.amazonaws.com/shinecosucan-test-frontend:latest"
    cpu: 512
    memory_mib: "916"
    port: 8002
    command: ["sh", "-c", "HOST=0.0.0.0 yarn dev"]
    environment:
      VENDURE_API_URL: "https://shinecosucan-admin.dev.yospace.ai/shop-api"
      PORT: "8002"

  backend:
    cpu: 512
    memory_mib: "512"
    port: 3000
    containers:
      app:
        image: "577638398727.dkr.ecr.eu-west-1.amazonaws.com/shinecosucan-test-backend:latest"
        command: ["npm", "run", "start:server"]
        environment:
          SUPERADMIN_USERNAME: "superadmin"
          SUPERADMIN_PASSWORD: "superadmin"
          APP_ENV: "dev"
          DB_USERNAME: "postgres"
          DB_NAME: "vendure"
          DB_PORT: "5432"
          ADMIN_API_HOST: "https://shinecosucan-admin.dev.yospace.ai"
          ADMIN_API_PORT: "443"
          COOKIE_SECRET: "5J6d2Llv0zkXsucalhIVnw"
          PORT: "3000"

      worker:
        image: "577638398727.dkr.ecr.eu-west-1.amazonaws.com/shinecosucan-test-backend:latest"
        command: ["npm", "run", "start:worker"]
        environment:
          DB_USERNAME: "postgres"
          DB_NAME: "vendure"
          DB_PORT: "5432"
          APP_ENV: "dev"
