project_name: shinecosucan
env: test

clusters:
  - name: main
    vpc: main
    availability_zones:
      - eu-west-1a
      - eu-west-1b
    instance_type: t3.small
    asg_min_capacity: 1
    asg_max_capacity: 4
    asg_desired_capacity: 2
    security_groups: [backend-sg]
    services:
      - name: frontend
        image: "577638398727.dkr.ecr.eu-west-1.amazonaws.com/shinecosucan-test-frontend:latest"
        cpu: 512
        memory_mib: "916"
        port: 8002
        command: ["sh", "-c", "HOST=0.0.0.0 yarn dev"]
        environment:
          VENDURE_API_URL: "https://shinecosucan-admin.dev.yospace.ai/shop-api"
          PORT: "8002"
        tg_name: main-alb-shinecosucan-app
      - name: backend
        cpu: 512
        memory_mib: "512"
        port: 3000
        tg_name: main-alb-shinecosucan-admin
        containers:
          - name: app
            image: "577638398727.dkr.ecr.eu-west-1.amazonaws.com/shinecosucan-test-backend:latest"
            command: ["npm", "run", "start:server"]
            environment:
              SUPERADMIN_USERNAME: "superadmin"
              SUPERADMIN_PASSWORD: "superadmin"
              APP_ENV: "dev"
              DB_USERNAME: "postgres"
              DB_NAME: "vendure"
              DB_PORT: "5432"
              ADMIN_API_HOST: "https://shinecosucan-admin.dev.yospace.ai"
              ADMIN_API_PORT: "443"
              COOKIE_SECRET: "5J6d2Llv0zkXsucalhIVnw"
              PORT: "3000"

          - name: worker
            image: "577638398727.dkr.ecr.eu-west-1.amazonaws.com/shinecosucan-test-backend:latest"
            command: ["npm", "run", "start:worker"]
            environment:
              DB_USERNAME: "postgres"
              DB_NAME: "vendure"
              DB_PORT: "5432"
              APP_ENV: "dev"
